#ifndef __GUIMainFrame__
#define __GUIMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <vector>
//#include "Shapes.h"

/** Implementing MainFrame */
class GUIMainFrame : public MainFrame
{
	protected:
		// Handlers for MainFrame events.
		void m_next_frame_button_clicked( wxCommandEvent& event );
		void m_previous_button_clicked( wxCommandEvent& event );
		void m_clear_button_clicked( wxCommandEvent& event );
		void m_back_button_clicked( wxCommandEvent& event );
		void m_circle_button_clicked( wxCommandEvent& event );
		void m_square_button_clicked( wxCommandEvent& event );
		void m_triangle_button_clicked( wxCommandEvent& event );
		void m_broken_line_clicked( wxCommandEvent& event );
		void m_curve_line_clicked( wxCommandEvent& event );
		void m_double_left_click_on_panel( wxMouseEvent& event );
		void m_coursor_moved_on_panel( wxMouseEvent& event );
		void m_right_clicked_on_panel( wxMouseEvent& event );
	public:
		/** Constructor */
		GUIMainFrame( wxWindow* parent );
	//// end generated class members

	private:
		//std::vector< std::shared_ptr<Shape> > m_shapes;
};

#endif // __GUIMainFrame__
